version: "3.9"

services:
  authentication:
    container_name: authentication
    build:
      context: ./
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - authentication-network
    command:
      [
        "sh",
        "-c",
        "until nc -z postgres 5432; do sleep 1; done; java -jar app.jar",
      ]

  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - 5432:5432
    networks:
      - authentication-network
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    networks:
      - authentication-network
    restart: unless-stopped

networks:
  authentication-network:
    driver: bridge