name: CI

on:
  push:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Build, test, and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests and generate Jacoco coverage
        run: mvn test jacoco:report

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=authentication \
            -Dsonar.host.url=http://sonarqube:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: target/*.jar
